<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <div class="card" style="width: 36rem;">
            <div class="card-body">

                <div class="d-flex justify-content-center">
                    <a href="/">
                        <img src="/assets/img/logo.png" width="50px" class="mb-3">
                    </a>
                </div>

                <div class="row">
                    <div class="col text-center mb-3">
                        <h2>Cadastro realizado com sucesso!</h2>
                    </div>
                </div>

                <div class="row">
                    <div class="col mb-3">
                        <a href="/" class="btn btn-danger btn-block">Clique aqui para fazer login!</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>