<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <div class="card" style="width: 36rem;">
            <div class="card-body">

                <div class="d-flex justify-content-center">
                    <a href="/">
                        <img src="/assets/img/logo.png" width="50px" class="mb-3"> 
                    </a>
                </div>

                <div class="row">
                    <div class="col text-center">
                        <h2>Crie sua conta</h2>
                    </div>
                </div>

                <div class="row">
                    <div class="col">

                        <form action="/registrar" method="post">
                            <div class="form-group">
                                <input type="text" value="<?= $this->view->usuario['nome'] ?>" name="nome" class="form-control form-control-lg" placeholder="Nome">
                            </div>

                            <div class="form-group">
                                <input type="text" value="<?= $this->view->usuario['email'] ?>" name="email" class="form-control form-control-lg" placeholder="E-mail">
                            </div>

                            <div class="form-group">
                                <input type="password" value="<?= $this->view->usuario['senha'] ?>" name="senha" class="form-control form-control-lg" placeholder="Senha">
                            </div>

                            <div class="mt-4 mb-4">
                                <span class="form-text">
                                    Ao inscrever-se clicanco no botão abaixo, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o uso de cookies.
                                </span>
                            </div>
                            <button type="submit" class="btn btn-lg btn-danger btn-block">Inscrever-se</button>

                            <?php if ($this->view->erroCadastro) { ?>

                                <small class="form-text text-danger">
                                    Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.
                                </small>

                            <?php } ?>

                        </form>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>