<header>

    <nav class="navbar navbar-expand-md sticky-top"><!-- navegaçao -->

        <a href="/dashboard" class="navbar-brand">
            <img src="assets/img/logo.png" height="35">
        </a>
        <h1>Sistema de gestão</h1>

        <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
            <i class="fas fa-bars text-white"></i>
        </button>

        <div class="collapse navbar-collapse" id="nav-principal">
            <ul class="navbar-nav ml-auto">

                <div class="top"><!-- Top -->

                    <button id="menu-btn">
                        <span class="material-icons-sharp">menu</span>
                    </button>

                    <div class="theme-toggler">
                        <span class="fas fa-moon active"></span>
                        <span class="fas fa-sun"></span>
                    </div>

                    <div class="profile">

                        <div class="info">
                            <p>Hey, <b class="success">Rafael</b></p>
                            <small class="text-muted">Admin</small>
                        </div>
                        <div class="profile-photo">
                            <img src="assets/img/profile-1.png" alt="profile-photo" width="40">
                        </div>

                    </div>

                </div><!-- /Top -->

                <!--
                <li>
                    <a href="#" class="btn btn-lg btn-danger" id="btn-sair">
                        Sair
                    </a>
                </li>
                -->
            </ul>
        </div>

    </nav><!-- /navegaçao -->

    <section>

        <div class="row">

            <div class="col-2"><!-- Coluna da esquerda -->

                <aside>
                    <div class="sidebar"><!-- Sidebar -->
                        <a href="/dashboard" class="active">
                            <span class="fas fa-th-large"></span>
                            Dashboard
                        </a>

                        <a href="#">
                            <span class="fas fa-users"></span>
                            Compradores
                        </a>

                        <a href="#">
                            <span class="fas fa-file-invoice-dollar"></span>
                            Pedidos
                        </a>

                        <a href="#">
                            <span class="fas fa-chart-line"></span>
                            Análises
                        </a>

                        <a href="#">
                            <span class="far fa-envelope"></span>
                            Mensagens
                            <div class="message-count">86</div>
                        </a>

                        <a href="/produtos">
                            <span class="fas fa-boxes"></span>
                            Produtos
                        </a>

                        <a href="#">
                            <span class="far fa-flag"></span>
                            Reclamações
                        </a>

                        <a href="#">
                            <span class="fas fa-cogs"></span>
                            Configurações
                        </a>

                        <a href="" data-toggle="modal" data-target=".bd-example-modal-lg">
                            <span class="fas fa-plus"></span>
                            Adicionar Produto
                        </a>

                        <a href="/sair">
                            <span class="fas fa-door-open"></span>
                            Sair
                        </a>
                    </div>
                </aside><!-- /Sidebar -->

            </div>

            <div class="col-7 m-3"><!-- Coluna central -->

                <div><!-- Painel administrativo -->
                    <h4>Painel Administrativo</h4>

                    <div class="card-deck mt-3 mb-4">
                        <div class="card custom-card border-dark mb-2">
                            <div class="card-body text-dark">
                                <h5 class="card-title">Vendas Totais</h5>
                                <h2>R$340,58</h2>
                                <hr>
                                <small class="card-text text-secondary">
                                    Últimas 24 horas
                                </small>
                            </div>
                        </div>

                        <div class="card custom-card border-dark mb-2">
                            <div class="card-body text-dark">
                                <h5 class="card-title">Despesas Totais</h5>
                                <h2>R$340,58</h2>
                                <hr>
                                <small class="card-text text-secondary">
                                    Últimas 24 horas
                                </small>
                            </div>
                        </div>

                        <div class="card custom-card border-dark mb-2">
                            <div class="card-body text-dark">
                                <h5 class="card-title">Lucro total</h5>
                                <h2>R$340,58</h2>
                                <hr>
                                <small class="form-text text-secondary">
                                    Últimas 24 horas
                                </small>
                            </div>
                        </div>
                    </div>

                    <h4>Pedidos Recentes</h4>

                    <div class="card custom-card border-dark mb-2">
                        <div class="card-body text-dark">

                            <table class="table table-borderless table-hover text-center"><!-- Tabela de produtos -->
                                <thead>
                                    <tr>
                                        <th scope="col">Nome do produto</th>
                                        <th scope="col">Número do pedido</th>
                                        <th scope="col">Pagamento</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Info</th>
                                    </tr>
                                </thead>
                                <?php foreach ($this->view->produtos as $id_produto => $produto) { ?>
                                    <tbody>
                                        <tr>
                                            <td><?= $produto['nome'] ?></td>
                                            <td><?= $produto['numero_de_serie'] ?></td>
                                            <td>Processando</td>
                                            <td>Pendente</td>
                                            <td><a href="#">Detalhes</a></td>
                                        </tr>
                                    </tbody>
                                <?php } ?>
                            </table>

                        </div>
                    </div>

                    <div class="text-center mt-4 mostrartudo">
                        <a href="#" style="text-decoration: none;">Mostrar Tudo</a>
                    </div>

                </div>

            </div>

            <div class="col m-3"><!-- Coluna da direita -->

                <div><!-- Atualizações recentes -->
                    <h4>Atualizações Recentes</h4>

                    <div class="card custom-card border-dark mt-3 mb-2">
                        <div class="card-body text-dark">
                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                            <hr>

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                            <hr>

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="mt-4"><!-- Análise de vendas -->

                    <h4>Análise de Vendas</h4>

                    <div class="card custom-card border-dark mt-3 mb-2">
                        <div class="card-body text-dark">

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="card custom-card border-dark mt-2 mb-2">
                        <div class="card-body text-dark">

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="card custom-card border-dark mt-2 mb-2">
                        <div class="card-body text-dark">

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>

            </div>

        </div>

    </section>

</header>