<header>

    <nav class="navbar navbar-expand-md sticky-top"><!-- navegaçao -->

        <a href="/dashboard" class="navbar-brand">
            <img src="assets/img/logo.png" height="35">
        </a>
        <h1>Sistema de gestão</h1>

        <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
            <i class="fas fa-bars text-white"></i>
        </button>

        <div class="collapse navbar-collapse" id="nav-principal">
            <ul class="navbar-nav ml-auto">

                <div class="top"><!-- Top -->

                    <button id="menu-btn">
                        <span class="material-icons-sharp">menu</span>
                    </button>

                    <div class="theme-toggler">
                        <span class="fas fa-moon active"></span>
                        <span class="fas fa-sun"></span>
                    </div>

                    <div class="profile">

                        <div class="info">
                            <p>Hey, <b>Rafael</b></p>
                            <small class="text-muted">Admin</small>
                        </div>
                        <div class="profile-photo">
                            <img src="assets/img/profile-1.png" alt="profile-photo" width="40">
                        </div>

                    </div>

                </div><!-- /Top -->

                <!--
                <li>
                    <a href="#" class="btn btn-lg btn-danger" id="btn-sair">
                        Sair
                    </a>
                </li>
                -->
            </ul>
        </div>

    </nav><!-- /navegaçao -->

    <section>

        <div class="row">

            <div class="col-2"><!-- Coluna da esquerda -->

                <aside>
                    <div class="sidebar"><!-- Sidebar -->
                        <a href="/dashboard" class="active">
                            <span class="fas fa-th-large"></span>
                            Dashboard
                        </a>

                        <a href="#">
                            <span class="fas fa-users"></span>
                            Compradores
                        </a>

                        <a href="#">
                            <span class="fas fa-file-invoice-dollar"></span>
                            Pedidos
                        </a>

                        <a href="#">
                            <span class="fas fa-chart-line"></span>
                            Análises
                        </a>

                        <a href="#">
                            <span class="far fa-envelope"></span>
                            Mensagens
                            <span class="message-count">86</span>
                        </a>

                        <a href="#">
                            <span class="fas fa-box-open"></span>
                            Produtos
                        </a>

                        <a href="#">
                            <span class="fas fa-flag"></span>
                            Reclamações
                        </a>

                        <a href="#">
                            <span class="fas fa-cogs"></span>
                            Configurações
                        </a>

                        <a href="#">
                            <span class="fas fa-plus"></span>
                            Adicionar Produto
                        </a>

                        <a href="/sair">
                            <span class="fas fa-door-open"></span>
                            Sair
                        </a>
                    </div>
                </aside><!-- /Sidebar -->

            </div>

            <div class="col-7 m-3"><!-- Coluna central -->

                <div><!-- Painel administrativo -->
                    <h4>Painel Administrativo</h4>

                    <div class="card-deck mt-3 mb-4">
                        <div class="card custom-card border-dark mb-2">
                            <div class="card-body text-dark">
                                <h5 class="card-title">Vendas Totais</h5>
                                <h2>R$340,58</h2>
                                <hr>
                                <small class="card-text text-secondary">
                                    Últimas 24 horas
                                </small>
                            </div>
                        </div>

                        <div class="card custom-card border-dark mb-2">
                            <div class="card-body text-dark">
                                <h5 class="card-title">Despesas Totais</h5>
                                <h2>R$340,58</h2>
                                <hr>
                                <small class="card-text text-secondary">
                                    Últimas 24 horas
                                </small>
                            </div>
                        </div>

                        <div class="card custom-card border-dark mb-2">
                            <div class="card-body text-dark">
                                <h5 class="card-title">Lucro total</h5>
                                <h2>R$340,58</h2>
                                <hr>
                                <small class="form-text text-secondary">
                                    Últimas 24 horas
                                </small>
                            </div>
                        </div>
                    </div>

                    <h4>Pedidos Recentes</h4>

                    <div class="card custom-card border-dark mb-2">
                        <div class="card-body text-dark">

                            <table class="table table-borderless table-hover text-center"><!-- Tabela de produtos -->
                                <thead>
                                    <tr>
                                        <th scope="col">Nome do produto</th>
                                        <th scope="col">Número do produto</th>
                                        <th scope="col">Pagamento</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Info</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th scope="row">Drone Speed Sparkles</th>
                                        <td>85631</td>
                                        <td>Processando</td>
                                        <td class="success">Pendente</td>
                                        <td>Detalhes</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Drone Speed Sparkles</th>
                                        <td>85631</td>
                                        <td>Processando</td>
                                        <td class="warning">Pendente</td>
                                        <td>Detalhes</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Drone Speed Sparkles</th>
                                        <td>85631</td>
                                        <td>Processando</td>
                                        <td class="warning">Pendente</td>
                                        <td>Detalhes</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Drone Speed Sparkles</th>
                                        <td>85631</td>
                                        <td>Processando</td>
                                        <td class="success">Pendente</td>
                                        <td>Detalhes</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Drone Speed Sparkles</th>
                                        <td>85631</td>
                                        <td>Processando</td>
                                        <td class="success">Pendente</td>
                                        <td>Detalhes</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Drone Speed Sparkles</th>
                                        <td>85631</td>
                                        <td>Processando</td>
                                        <td class="warning">Pendente</td>
                                        <td>Detalhes</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Drone Speed Sparkles</th>
                                        <td>85631</td>
                                        <td>Processando</td>
                                        <td class="warning">Pendente</td>
                                        <td>Detalhes</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Drone Speed Sparkles</th>
                                        <td>85631</td>
                                        <td>Processando</td>
                                        <td class="danger">Pendente</td>
                                        <td>Detalhes</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Drone Speed Sparkles</th>
                                        <td>85631</td>
                                        <td>Processando</td>
                                        <td class="success">Pendente</td>
                                        <td>Detalhes</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Drone Speed Sparkles</th>
                                        <td>85631</td>
                                        <td>Processando</td>
                                        <td class="success">Pendente</td>
                                        <td>Detalhes</td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>
                    </div>

                    <div class="text-center mt-4">
                        <a href="#" class="link-custom">Mostrar Tudo</a>
                    </div>

                </div>

            </div>

            <div class="col m-3"><!-- Coluna da direita -->

                <div><!-- Atualizações recentes -->
                    <h4>Atualizações Recentes</h4>

                    <div class="card custom-card border-dark mt-3 mb-2">
                        <div class="card-body text-dark">
                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                            <hr>

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                            <hr>

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="mt-4"><!-- Análise de vendas -->

                    <h4>Análise de Vendas</h4>

                    <div class="card custom-card border-dark mt-3 mb-2">
                        <div class="card-body text-dark">

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="card custom-card border-dark mt-2 mb-2">
                        <div class="card-body text-dark">

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="card custom-card border-dark mt-2 mb-2">
                        <div class="card-body text-dark">

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>

                <div><!-- Adicionar produtos -->

                    <button class="btn btn-lg btn-custom btn-dark btn-block" data-toggle="modal" data-target=".bd-example-modal-lg">
                        <span class="fas fa-solid fa-plus mr-2"></span>
                        Adicionar Produtos
                    </button>

                </div>

            </div>

        </div>

    </section>

    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true"><!-- Modal -->
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">

                    <h3 class="modal-title">Adicionar novo produto</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>

                <div class="modal-body">
                    <form action="/adicionar_produto" method="post">
                        <div class="form-row">
                            <div class="form-group col-md-3">
                                <label for="categoria" class="col-form-label col-form-label-lg">Categoria</label>
                                <select id="inputCategoria" name="categoria" class="form-control form-control-lg" required><!-- ATENÇÃO AQUI -->
                                    <option value="" selected>Escolha uma opção</option>
                                    <option value="">Computadores</option>
                                    <option value="1">Drones</option>
                                    <option value="2">Fontes</option>
                                    <option value="3">Headsets</option>
                                    <option value="4">Microfones</option>
                                    <option value="5">Monitores</option>
                                    <option value="6">Mouses</option>
                                    <option value="7">Periféricos</option>
                                    <option value="8">Smartphones</option>
                                    <option value="9">Teclados</option>
                                    <option value="10">Utilitários</option>
                                    <option value="11">Wearables</option>
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="marca" class="col-form-label col-form-label-lg">Marca</label>
                                <input type="text" class="form-control form-control-lg" name="marca" id="inputMarca" placeholder="Marca do produto" required>
                            </div>
                            <div class="form-group col-md-5">
                                <label for="nome" class="col-form-label col-form-label-lg">Nome</label>
                                <input type="text" class="form-control form-control-lg" name="nome" id="inputNome" placeholder="Nome do produto" required>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-2">
                                <label for="quantidade" class="col-form-label col-form-label-lg">Quantidade</label>
                                <input type="number" class="form-control form-control-lg" id="inputQuantidade" name="quantidade" placeholder="0" required>
                            </div>
                            <div class="form-group col-md-5">
                                <label for="numero_de_serie" class="col-form-label col-form-label-lg">Número de Série</label>
                                <input type="number" class="form-control form-control-lg" id="inputNumeroDeSerie" name="numero_de_serie" placeholder="Número de Série" required>
                            </div>
                            <div class="form-group col-md-5">
                                <label for="numero_da_nota_fiscal" class="col-form-label col-form-label-lg">Número da Nota Fiscal</label>
                                <input type="number" class="form-control form-control-lg" id="inputNumeroDaNotaFiscal" name="numero_da_nota_fiscal" placeholder="Número da Nota Fiscal" required>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="custoDoProduto" class="col-form-label col-form-label-lg">Preço de custo</label>
                                <input type="number" class="form-control form-control-lg" id="inputCustoDoProduto" name="custo_do_produto" placeholder="R$" required>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="precoDoProduto" class="col-form-label col-form-label-lg">Preço Final</label>
                                <input type="number" class="form-control form-control-lg" id="inputPrecoDoProtudo"name="preco_do_produto" placeholder="R$" required>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="descricao" class="col-form-label col-form-label-lg">Descrição</label>
                                <textarea class="form-control form-control-lg" id="inputDescricao" name="descricao" rows="10"></textarea>
                            </div>
                        </div>
                        <div class="form-row">
                            <button type="submit" class="btn btn-lg btn-success mx-auto">Cadastrar Produto</button>
                        </div>
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-lg btn-secondary" onclick="" data-dismiss="modal">Fechar</button>
                </div>

            </div>
        </div>
    </div><!-- /Modal -->



</header>