<header>

    <nav class="navbar navbar-expand-md sticky-top"><!-- navegaçao -->

        <a href="/dashboard" class="navbar-brand">
            <img src="assets/img/logo.png" height="35">
        </a>
        <h1>Sistema de gestão</h1>

        <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
            <i class="fas fa-bars text-white"></i>
        </button>

        <div class="collapse navbar-collapse" id="nav-principal">
            <ul class="navbar-nav ml-auto">

                <div class="top"><!-- Top -->

                    <button id="menu-btn">
                        <span class="material-icons-sharp">menu</span>
                    </button>

                    <div class="theme-toggler">
                        <span class="fas fa-moon active"></span>
                        <span class="fas fa-sun"></span>
                    </div>

                    <div class="profile">

                        <div class="info">
                            <p>Hey, <b>Rafael</b></p>
                            <small class="text-muted">Admin</small>
                        </div>
                        <div class="profile-photo">
                            <img src="assets/img/profile-1.png" alt="profile-photo" width="40">
                        </div>

                    </div>

                </div><!-- /Top -->

                <!--
                <li>
                    <a href="#" class="btn btn-lg btn-danger" id="btn-sair">
                        Sair
                    </a>
                </li>
                -->
            </ul>
        </div>

    </nav><!-- /navegaçao -->

    <section>

        <div class="row">

            <div class="col-2"><!-- Coluna da esquerda -->

                <aside>
                    <div class="sidebar"><!-- Sidebar -->
                        <a href="/dashboard">
                            <span class="fas fa-th-large"></span>
                            Dashboard
                        </a>

                        <a href="#">
                            <span class="fas fa-users"></span>
                            Compradores
                        </a>

                        <a href="#">
                            <span class="fas fa-file-invoice-dollar"></span>
                            Pedidos
                        </a>

                        <a href="#">
                            <span class="fas fa-chart-line"></span>
                            Análises
                        </a>

                        <a href="#">
                            <span class="far fa-envelope"></span>
                            Mensagens
                            <span class="message-count">86</span>
                        </a>

                        <a href="/produtos" class="active">
                            <span class="fas fa-boxes"></span>
                            Produtos
                        </a>

                        <a href="#">
                            <span class="far fa-flag"></span>
                            Reclamações
                        </a>

                        <a href="#">
                            <span class="fas fa-cogs"></span>
                            Configurações
                        </a>

                        <a href="#">
                            <span class="fas fa-plus"></span>
                            Adicionar Produto
                        </a>

                        <a href="/sair">
                            <span class="fas fa-door-open"></span>
                            Sair
                        </a>
                    </div>
                </aside><!-- /Sidebar -->

            </div>

            <div class="col-7 m-3"><!-- Coluna central -->

                <div><!-- Filtro -->

                    <div class="mb-4">
                        <div class="card custom-card border-dark mb-2">
                            <div class="card-body text-dark">
                                <h4 class="card-title">Pesquisar</h4>
                                <form action="#" method="post">
                                    <div class="form-row form-inline justify-content-center">
                                        <div class="form-group col-auto">
                                            <label for="categoria" class="col-form-label col-form-label-lg">Categoria </label>
                                            <select id="inputCategoria" name="categoria" class="form-control"><!-- ATENÇÃO AQUI -->
                                                <option value="" selected>Escolha uma opção</option>
                                                <option value="Computadores">Computadores</option>
                                                <option value="Drones">Drones</option>
                                                <option value="Fontes">Fontes</option>
                                                <option value="Headsets">Headsets</option>
                                                <option value="Microfones">Microfones</option>
                                                <option value="Monitores">Monitores</option>
                                                <option value="Mouses">Mouses</option>
                                                <option value="Periféricos">Periféricos</option>
                                                <option value="Smartphones">Smartphones</option>
                                                <option value="Teclados">Teclados</option>
                                                <option value="Utilitários">Utilitários</option>
                                                <option value="Wearables">Wearables</option>
                                            </select>
                                        </div>

                                        <div class="form-group col-auto">
                                            <label for="marca" class="col-form-label col-form-label-lg">Marca </label>
                                            <input type="text" class="form-control" name="marca" id="inputMarca" placeholder="Marca">
                                        </div>

                                        <div class="form-group col-auto">
                                            <label for="nome" class="col-form-label col-form-label-lg">Nome </label>
                                            <input type="text" class="form-control" name="nome" id="inputNome" placeholder="Nome do produto">
                                        </div>

                                        <div class="form-group col-auto">
                                            <label for="id" class="col-form-label col-form-label-lg">Id </label>
                                            <input type="number" class="form-control" name="id" id="inputId" placeholder="Id">
                                        </div>

                                    </div>

                                    <div class="form-row form-inline justify-content-center">
                                        <div class="form-group col-auto">
                                            <label for="numero_de_serie" class="col-form-label col-form-label-lg">N/S </label>
                                            <input type="number" class="form-control" name="numero_de_serie" id="inputNumeroDeSerie" placeholder="Número de série">
                                        </div>

                                        <div class="form-group col-auto">
                                            <label for="numero_da_nota_fiscal" class="col-form-label col-form-label-lg">Nota Fiscal </label>
                                            <input type="number" class="form-control" name="numero_de_serie" id="inputNumeroDeSerie" placeholder="Número de série">
                                        </div>

                                        <div class="form-group btn-filtrar ml-5">
                                            <button class="btn btn-lg btn-success">
                                                <i class="fas fa-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>

                    <h4>Produtos</h4>

                    <div class="card custom-card border-dark mb-3">
                        <div class="card-body text-dark">

                            <table class="table table-borderless table-hover text-center"><!-- Tabela de produtos -->
                                <thead>
                                    <tr>
                                        <th scope="col">Categoria</th>
                                        <th scope="col">Nome</th>
                                        <th scope="col">Marca</th>
                                        <th scope="col">Estoque</th>
                                        <th scope="col">S/N</th>
                                        <th scope="col">Info</th>

                                    </tr>
                                </thead>
                                <?php foreach ($this->view->produtos as $id_produto => $produto) { ?>
                                    <tbody>
                                        <tr>
                                            <td><?= $produto['categoria'] ?></td>
                                            <td><?= $produto['nome'] ?></td>
                                            <td><?= $produto['marca'] ?></td>
                                            <td><?= $produto['quantidade'] ?></td>
                                            <td><?= $produto['numero_de_serie'] ?></td>
                                            <td><a href="#">Detalhes</a></td>
                                        </tr>
                                    </tbody>
                                <?php } ?>
                            </table>

                        </div>
                    </div>

                    <div class="text-center mt-4">
                        <a href="#" style="text-decoration: none;">Mostrar Tudo</a>
                    </div>

                </div>

            </div>

            <div class="col m-3"><!-- Coluna da direita -->

                <div><!-- Atualizações recentes -->
                    <h4>Atualizações Recentes</h4>

                    <div class="card custom-card border-dark mt-3 mb-2">
                        <div class="card-body text-dark">
                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                            <hr>

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                            <hr>

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="mt-4"><!-- Análise de vendas -->

                    <h4>Análise de Vendas</h4>

                    <div class="card custom-card border-dark mt-3 mb-2">
                        <div class="card-body text-dark">

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="card custom-card border-dark mt-2 mb-2">
                        <div class="card-body text-dark">

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="card custom-card border-dark mt-2 mb-2">
                        <div class="card-body text-dark">

                            <div class="row">
                                <div class="col-2">
                                    <img src="assets/img/profile-1.png" width="40">
                                </div>
                                <div class="col">
                                    <p><b>Hugo Maciel</b> recebeu seu pedido "Drone Speed Sparkles PRO".</p>
                                    <small class="text-muted">2 minutos atrás</small>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>

                <div><!-- Adicionar produtos -->

                    <button class="btn btn-lg btn-custom btn-dark btn-block" data-toggle="modal" data-target=".bd-example-modal-lg">
                        <span class="fas fa-solid fa-plus mr-2"></span>
                        Adicionar Produtos
                    </button>

                </div>

            </div>

        </div>

    </section>

    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true"><!-- Modal -->
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">

                    <h3 class="modal-title">Adicionar novo produto</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>

                <div class="modal-body">
                    <form action="/adicionar_produto" method="post">
                        <div class="form-row">
                            <div class="form-group col-md-3">
                                <label for="categoria" class="col-form-label col-form-label-lg">Categoria</label>
                                <select id="inputCategoria" name="categoria" class="form-control form-control-lg" required><!-- ATENÇÃO AQUI -->
                                    <option value="" selected>Escolha uma opção</option>
                                    <option value="Computadores">Computadores</option>
                                    <option value="Drones">Drones</option>
                                    <option value="Fontes">Fontes</option>
                                    <option value="Headsets">Headsets</option>
                                    <option value="Microfones">Microfones</option>
                                    <option value="Monitores">Monitores</option>
                                    <option value="Mouses">Mouses</option>
                                    <option value="Periféricos">Periféricos</option>
                                    <option value="Smartphones">Smartphones</option>
                                    <option value="Teclados">Teclados</option>
                                    <option value="Utilitários">Utilitários</option>
                                    <option value="Wearables">Wearables</option>
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="marca" class="col-form-label col-form-label-lg">Marca</label>
                                <input type="text" class="form-control form-control-lg" name="marca" id="inputMarca" placeholder="Marca do produto" required>
                            </div>
                            <div class="form-group col-md-5">
                                <label for="nome" class="col-form-label col-form-label-lg">Nome</label>
                                <input type="text" class="form-control form-control-lg" name="nome" id="inputNome" placeholder="Nome do produto" required>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-2">
                                <label for="quantidade" class="col-form-label col-form-label-lg">Quantidade</label>
                                <input type="number" class="form-control form-control-lg" id="inputQuantidade" name="quantidade" placeholder="0" required>
                            </div>
                            <div class="form-group col-md-5">
                                <label for="numero_de_serie" class="col-form-label col-form-label-lg">Número de Série</label>
                                <input type="number" class="form-control form-control-lg" id="inputNumeroDeSerie" name="numero_de_serie" placeholder="Número de Série" required>
                            </div>
                            <div class="form-group col-md-5">
                                <label for="numero_da_nota_fiscal" class="col-form-label col-form-label-lg">Número da Nota Fiscal</label>
                                <input type="number" class="form-control form-control-lg" id="inputNumeroDaNotaFiscal" name="numero_da_nota_fiscal" placeholder="Número da Nota Fiscal" required>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="custoDoProduto" class="col-form-label col-form-label-lg">Preço de custo</label>
                                <input type="number" class="form-control form-control-lg" id="inputCustoDoProduto" name="custo_do_produto" placeholder="R$" required>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="precoDoProduto" class="col-form-label col-form-label-lg">Preço Final</label>
                                <input type="number" class="form-control form-control-lg" id="inputPrecoDoProtudo" name="preco_do_produto" placeholder="R$" required>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="descricao" class="col-form-label col-form-label-lg">Descrição</label>
                                <textarea class="form-control form-control-lg" id="inputDescricao" name="descricao" rows="10"></textarea>
                            </div>
                        </div>
                        <div class="form-row">
                            <button type="submit" class="btn btn-lg btn-success mx-auto">Cadastrar Produto</button>
                        </div>
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-lg btn-secondary" onclick="" data-dismiss="modal">Fechar</button>
                </div>

            </div>
        </div>
    </div><!-- /Modal -->

</header>