<html lang="pt-BR">

<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Sistema de gestão</title>

	<link rel="icon" href="/assets/img/favicon.png">

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="/assets/css/style.css">

</head>

<body>
	<?= $this->content() ?>

	<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true"><!-- Modal -->
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">

                    <h3 class="modal-title">Adicionar novo produto</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>

                <div class="modal-body">
                    <form action="/adicionar_produto" method="post">
                        <div class="form-row">
                            <div class="form-group col-md-3">
                                <label for="categoria" class="col-form-label col-form-label-lg">Categoria</label>
                                <select id="inputCategoria" name="categoria" class="form-control form-control-lg" required><!-- ATENÇÃO AQUI -->
                                    <option value="" selected>Escolha uma opção</option>
                                    <option value="Computadores">Computadores</option>
                                    <option value="Drones">Drones</option>
                                    <option value="Fontes">Fontes</option>
                                    <option value="Headsets">Headsets</option>
                                    <option value="Microfones">Microfones</option>
                                    <option value="Monitores">Monitores</option>
                                    <option value="Mouses">Mouses</option>
                                    <option value="Periféricos">Periféricos</option>
                                    <option value="Smartphones">Smartphones</option>
                                    <option value="Teclados">Teclados</option>
                                    <option value="Utilitários">Utilitários</option>
                                    <option value="Wearables">Wearables</option>
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="marca" class="col-form-label col-form-label-lg">Marca</label>
                                <input type="text" class="form-control form-control-lg" name="marca" id="inputMarca" placeholder="Marca do produto" required>
                            </div>
                            <div class="form-group col-md-5">
                                <label for="nome" class="col-form-label col-form-label-lg">Nome</label>
                                <input type="text" class="form-control form-control-lg" name="nome" id="inputNome" placeholder="Nome do produto" required>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-2">
                                <label for="quantidade" class="col-form-label col-form-label-lg">Quantidade</label>
                                <input type="number" class="form-control form-control-lg" id="inputQuantidade" name="quantidade" placeholder="0" required>
                            </div>
                            <div class="form-group col-md-5">
                                <label for="numero_de_serie" class="col-form-label col-form-label-lg">Número de Série</label>
                                <input type="number" class="form-control form-control-lg" id="inputNumeroDeSerie" name="numero_de_serie" placeholder="Número de Série" required>
                            </div>
                            <div class="form-group col-md-5">
                                <label for="numero_da_nota_fiscal" class="col-form-label col-form-label-lg">Número da Nota Fiscal</label>
                                <input type="number" class="form-control form-control-lg" id="inputNumeroDaNotaFiscal" name="numero_da_nota_fiscal" placeholder="Número da Nota Fiscal" required>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="custoDoProduto" class="col-form-label col-form-label-lg">Preço de custo</label>
                                <input type="number" class="form-control form-control-lg" id="inputCustoDoProduto" name="custo_do_produto" placeholder="R$" required>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="precoDoProduto" class="col-form-label col-form-label-lg">Preço Final</label>
                                <input type="number" class="form-control form-control-lg" id="inputPrecoDoProtudo" name="preco_do_produto" placeholder="R$" required>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="descricao" class="col-form-label col-form-label-lg">Descrição</label>
                                <textarea class="form-control form-control-lg" id="inputDescricao" name="descricao" rows="10"></textarea>
                            </div>
                        </div>
                        <div class="form-row">
                            <button type="submit" class="btn btn-lg btn-success mx-auto">Cadastrar Produto</button>
                        </div>
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-lg btn-secondary" onclick="" data-dismiss="modal">Fechar</button>
                </div>

            </div>
        </div>
    </div><!-- /Modal -->
	
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	
</body>

</html>